[package]
name = "rustprompt"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"

anyhow = "1"
thiserror = "2.0.12"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
reedline = "0.39.0"
